name: vox_environment
channels:
  - conda-forge
  - gurobi
  - http://conda.anaconda.org/gurobi
  - ibmdecisionoptimization
  - defaults
dependencies:
  - apipkg=1.5
  - appdirs=1.4.3
  - asn1crypto=1.3.0
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - black=19.3b0
  - blas=1.0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - click=7.0
  - colorama=0.4.3
  - colour=0.1.5
  - cryptography=2.8
  - dask=2.10.1
  - decorator=4.4.1
  - docplex=2.12.*
  - execnet=1.7.1
  - flask-cors=3.0.8
  - flask-marshmallow=0.11.0
  - flask-migrate=2.4.0
  - flask-sqlalchemy=2.4.0
  - flask=1.1.1
  - gurobi
  - idna=2.8
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython_genutils=0.2.0
  - ipython=7.11.1
  - itsdangerous=1.1.0
  - jedi=0.15.2
  - jinja2=2.10.3
  - jsonschema=3.2.0
  - jupyter_client=5.3.4
  - jupyter_core=4.6.1
  - libsodium=1.0.16
  - markupsafe=1.1.1
  - marshmallow-sqlalchemy=0.22.2
  - marshmallow=3.5.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - mkl-service=2.3.0
  - mkl=2019.4
  - more-itertools=8.0.2
  - mypy_extensions=0.4.3
  - mypy=0.770
  - mysql-connector-c=6.1.11
  - mysql-connector-python=8.0.18
  - numpy-base=1.17.4
  - numpy=1.17.4
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=1.0.1
  - parso=0.5.2
  - pickleshare=0.7.5
  - pip=20.0.2
  - pluggy=0.13.1
  - prompt_toolkit=3.0.2
  - psutil=5.6.7
  - py=1.8.0
  - pyarrow=0.11.1
  - pycodestyle=2.5.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyjnius
  - pymysql=0.9.3
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyrsistent=0.15.6
  - pysocks=1.7.1
  - pytest-forked=1.1.3
  - pytest-xdist=1.30.0
  - pytest=5.3.2
  - python-dateutil=2.8.1
  - python=3.7.6
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=18.1.0
  - requests=2.22.0
  - scipy=1.4.1
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - toml=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - wcwidth=0.1.7
  - werkzeug=0.16.0
  - wheel=0.33.6
  - xlrd=1.2.0
  - xlsxwriter=1.2.6
  - yaml=0.2.2
  - zeromq=4.3.1
  - zipp=0.6.0
  - pip:
      - flask-swagger-ui==3.20.9
      - blackcellmagic==0.0.2
      - flask-api==2.0
      - pytest-flask==0.15.0
