#!/bin/bash

####################################################################################
## quick script that backs up the crontab as currently written to a gzipped directory 
###################################################################################

crontab -l > ~/Dropbox/scripts/bash/script_settings/crontab_backup 

####################################################################################
# Script written by David Donovan                                                  #
# December 2019                                                                    #
####################################################################################
