#!/bin/bash

## ##
name=$1
name_nsuf="${name%.*}"
mkdir -p $name_nsuf

echo "saving files under name ${name}"

## ##
name_pdf_suffix="${name_nsuf}.pdf"

## ##
loffice --headless --convert-to pdf:"impress_pdf_Export:ExportNotesPages=True" $name 
pdftoppm $name_pdf_suffix $name_nsuf/output -png -rx 150 -ry 150

## echo the name to indicate that we are done  ##
echo '...done, pictures saved to output directory'
