#!/bin/bash
## argument 1 is the csv file name where the names are stored

copy_YT_vid_from_csv_to_directory() { 

count=0
while IFS=, read -r url dir_save; do
  	youtube-dl --download-archive "~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/$dir_save/downloaded.txt" --no-post-overwrites -ciwx -f mp4 -o "~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/$dir_save/%(title)s.%(ext)s" $url
  
  [[ "$code" == *","* ]] && echo "$name $code" && ((++count))
done < $1; \
}

CSV_INPUT=script_settings/kids_lists_for_download.csv
copy_YT_vid_from_csv_to_directory $CSV_INPUT 
