#!/bin/bash

## the path for the new open projects ##
save_path='/home/dave/Dropbox/BloggingFileFolder/OpenProjects/'

if [ $# -eq 0 ] 
  then
    dir_name=$(date +"%m-%d-%y" )'-video'
  else 
    dir_name=$1'-video'
fi
  
## ##
full_dir_name="$save_path$dir_name"

## create the directory for the new, open project if it does not already exist ##
mkdir $full_dir_name

## copy over the power point presentation and the baseline project ##
cp -n /home/dave/Dropbox/scripts/bash/templates/videoPresentationTemplate.odp $full_dir_name

## rename the file to match the project name ##
new_file_name=$full_dir_name'/'$dir_name'Presentation.odp'
mv $full_dir_name'/videoPresentationTemplate.odp' $new_file_name

## output the empty ##
convert_present_to_image $new_file_name

## create the audacity and kdenlive projects ##

## ##


