#!/bin/bash
#The script downloads the song from YouTube using youtube-dl command line utitlity. After that it calls MusicBrainz Picard (MP3 ID3 Tagger) to correct the metadata. Post that, it calls mp3info to display the ID3 tag information as well as prompts the user whether they want to play the song.

pip3 install --upgrade youtube-dl

# 1 - download the classical playlist PLRbcQXWEJAJpVlnuqiqqZ27FmWlxka62l 
youtube-dl --download-archive ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_classical/downloaded.txt --no-post-overwrites -ciwx --audio-format mp3 --yes-playlist -o "~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_classical/%(title)s.%(ext)s" PLRbcQXWEJAJpVlnuqiqqZ27FmWlxka62l

it=0
for x in ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_classical/*.mp3; do 
   name="${x##*/}" 
   name_nsuf="${name%.*}"
   let it=it+1
   mp3info -a "classical_mix" -n "$it" -l "classical_mix" -t "$name_nsuf" "$x"
done

# 2 - download the synth playlist PLRbcQXWEJAJpxUEekZez2CrHBKOnjlE_z
youtube-dl --download-archive ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_Retro_Synth/downloaded.txt --no-post-overwrites -ciwx --audio-format mp3 --yes-playlist -o "~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_Retro_Synth/%(title)s.%(ext)s" PLRbcQXWEJAJpxUEekZez2CrHBKOnjlE_z
it=0
for x in ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_Retro_Synth/*.mp3; do 
   name="${x##*/}" 
   name_nsuf="${name%.*}"
   let it=it+1
   mp3info -a "ret_synth_mix" -n $it -l "ret_synth_mix" -t "$name_nsuf" "$x"
done

# 3 - download the video games playlist PLRbcQXWEJAJpUF_9RyWCgnoGe2QJmwU2_
youtube-dl --download-archive ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_game_mix/downloaded.txt --no-post-overwrites -ciwx --audio-format mp3 --yes-playlist -o "~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_game_mix/%(title)s.%(ext)s" PLRbcQXWEJAJpUF_9RyWCgnoGe2QJmwU2_
it=0
for x in ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_game_mix/*.mp3; do 
   name="${x##*/}" 
   name_nsuf="${name%.*}"
   let it=it+1
   mp3info -a "game_mix" -n $it -l "game_mix" -t "$name_nsuf" "$x"
done

# 4 - download the video games playlist PLRbcQXWEJAJoEUghv3ysg2T7y-lAecGdj
youtube-dl --download-archive ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_coding_music/downloaded.txt --no-post-overwrites -ciwx --audio-format mp3 --yes-playlist -o "~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_coding_music/%(title)s.%(ext)s" PLRbcQXWEJAJoEUghv3ysg2T7y-lAecGdj
it=0
for x in  ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists/YT_coding_music/*.mp3; do 
   name="${x##*/}" 
   name_nsuf="${name%.*}"
   let it=it+1
   mp3info -a "code_mix" -n $it -l "code_mix" -t "$name_nsuf" "$x"
done

echo "Finished syncing the YT playlist to the HD-Dropbox folder"
exit
