#!/bin/bash

####################################################################################
## quick script that writes all media inside of the folders ~/Dropbox/media
## to the folder 
###################################################################################

rsync -avu --delete ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Music ~/Music  
rsync -avu --delete ~/Dropbox/HelensMusic ~/Music/HelensMusic  
rsync -avu --delete ~/Dropbox/MediaFileFolder/MusicAndPlaylists/Playlists ~/Music/PlaylistsAdd

####################################################################################
# Script written by David Donovan                                                  #
# December 2019                                                                    #
####################################################################################
