#!/bin/bash
####################################################################################
## a script that runs all of our synchronization programs
#
###################################################################################
## current we don't use this, but I am keeping this around in case we need to generalize

LOG_LOCATION='/home/dave/Dropbox/scripts/bash'
SCRIPT_LOCATION='/home/dave/Dropbox/scripts/bash'
export PATH=$PATH:$SCRIPT_LOCATION

sync_filesystem_to_webserver.sh
sync_music_to_mediacenter.sh
back_up_crontab_dir.sh
sync_confirm.sh >> $LOG_LOCATION/log.txt

echo "full sync complete"

####################################################################################
# Script written by David Donovan                                                  #
# December 2019                                                                    #
####################################################################################
